name: example
description: A sample project that show how to use vcshooks command line script.
homepage: https://github.com/bitsydarel/vcshooks
repository: https://github.com/bitsydarel/vcshooks
issue_tracker: https://github.com/bitsydarel/vcshooks/issues

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  flutter_code_style: ^2.1.1
